"""Init

Revision ID: 4fd1b6aa7c53
Revises: 
Create Date: 2026-04-13 21:33:18.441942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fd1b6aa7c53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('google_ads_customer_id', sa.String(length=20), nullable=True),
    sa.Column('meta_ad_account_id', sa.String(length=50), nullable=True),
    sa.Column('shopify_shop_domain', sa.String(length=255), nullable=True),
    sa.Column('ga4_property_id', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clients_active', 'clients', ['is_active'], unique=False)
    op.create_index('idx_clients_type', 'clients', ['type'], unique=False)
    op.create_table('client_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'source', name='uq_connection_client_source')
    )
    op.create_index('idx_connections_client', 'client_connections', ['client_id'], unique=False)
    op.create_index('idx_connections_source', 'client_connections', ['source'], unique=False)
    op.create_table('pull_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('rows_pulled', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pull_jobs_client', 'pull_jobs', ['client_id'], unique=False)
    op.create_index('idx_pull_jobs_created', 'pull_jobs', ['created_at'], unique=False)
    op.create_index('idx_pull_jobs_source', 'pull_jobs', ['source'], unique=False)
    op.create_index('idx_pull_jobs_status', 'pull_jobs', ['status'], unique=False)
    op.create_table('ga4_channel_breakdown',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('channel_group', sa.String(length=100), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'channel_group', name='uq_ga4_ch_unique')
    )
    op.create_index('idx_ga4_ch_client_date', 'ga4_channel_breakdown', ['client_id', 'report_date'], unique=False)
    op.create_table('ga4_device_breakdown',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('device_category', sa.String(length=50), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'device_category', name='uq_ga4_dev_unique')
    )
    op.create_index('idx_ga4_dev_client_date', 'ga4_device_breakdown', ['client_id', 'report_date'], unique=False)
    op.create_table('ga4_revenue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('purchase_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transactions', sa.Integer(), nullable=True),
    sa.Column('avg_purchase_revenue', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('session_conversion_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', name='uq_ga4_rev_unique')
    )
    op.create_index('idx_ga4_rev_client_date', 'ga4_revenue', ['client_id', 'report_date'], unique=False)
    op.create_table('google_ads_campaign',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_cpc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conversion_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('conv_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_per_conv', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('impression_share', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'campaign_id', 'report_date', name='uq_gads_camp_client_campaign_date')
    )
    op.create_index('idx_gads_camp_client_date', 'google_ads_campaign', ['client_id', 'report_date'], unique=False)
    op.create_table('google_ads_demographics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_range', sa.String(length=30), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'gender', 'age_range', name='uq_gads_demo_unique')
    )
    op.create_index('idx_gads_demo_client_date', 'google_ads_demographics', ['client_id', 'report_date'], unique=False)
    op.create_table('google_ads_keywords',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('keyword_text', sa.String(length=500), nullable=True),
    sa.Column('match_type', sa.String(length=20), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_cpc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gads_kw_client_date', 'google_ads_keywords', ['client_id', 'report_date'], unique=False)
    op.create_table('google_ads_search_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('search_term', sa.Text(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('avg_cpc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conv_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gads_st_client_date', 'google_ads_search_terms', ['client_id', 'report_date'], unique=False)
    op.create_table('google_ads_time_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('segment_type', sa.String(length=15), nullable=False),
    sa.Column('segment_value', sa.String(length=20), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'segment_type', 'segment_value', name='uq_gads_ts_unique')
    )
    op.create_index('idx_gads_ts_client_date', 'google_ads_time_segments', ['client_id', 'report_date'], unique=False)
    op.create_table('meta_campaign',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cpc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('frequency', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('cpm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_per_result', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conv_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('roas', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'campaign_id', 'report_date', name='uq_meta_camp_unique')
    )
    op.create_index('idx_meta_camp_client_date', 'meta_campaign', ['client_id', 'report_date'], unique=False)
    op.create_table('meta_demographics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('conversions', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'gender', 'age_group', name='uq_meta_demo_unique')
    )
    op.create_index('idx_meta_demo_client_date', 'meta_demographics', ['client_id', 'report_date'], unique=False)
    op.create_table('meta_leadgen',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('leads', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_per_lead', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('lead_form_opens', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('form_completion_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('link_clicks', sa.BigInteger(), nullable=True),
    sa.Column('landing_page_views', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'campaign_id', 'report_date', name='uq_meta_lg_unique')
    )
    op.create_index('idx_meta_lg_client_date', 'meta_leadgen', ['client_id', 'report_date'], unique=False)
    op.create_table('meta_time_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('segment_type', sa.String(length=10), nullable=False),
    sa.Column('segment_value', sa.String(length=20), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'segment_type', 'segment_value', name='uq_meta_ts_unique')
    )
    op.create_index('idx_meta_ts_client_date', 'meta_time_segments', ['client_id', 'report_date'], unique=False)
    op.create_table('shopify_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('shopify_order_id', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('customer_orders_count', sa.Integer(), nullable=True),
    sa.Column('is_new_customer', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'shopify_order_id', name='uq_shopify_order_unique')
    )
    op.create_index('idx_shopify_orders_client_date', 'shopify_orders', ['client_id', 'order_date'], unique=False)
    op.create_table('shopify_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('pull_job_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('product_title', sa.String(length=500), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pull_job_id'], ['pull_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'report_date', 'product_title', name='uq_shopify_product_unique')
    )
    op.create_index('idx_shopify_products_client_date', 'shopify_products', ['client_id', 'report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shopify_products_client_date', table_name='shopify_products')
    op.drop_table('shopify_products')
    op.drop_index('idx_shopify_orders_client_date', table_name='shopify_orders')
    op.drop_table('shopify_orders')
    op.drop_index('idx_meta_ts_client_date', table_name='meta_time_segments')
    op.drop_table('meta_time_segments')
    op.drop_index('idx_meta_lg_client_date', table_name='meta_leadgen')
    op.drop_table('meta_leadgen')
    op.drop_index('idx_meta_demo_client_date', table_name='meta_demographics')
    op.drop_table('meta_demographics')
    op.drop_index('idx_meta_camp_client_date', table_name='meta_campaign')
    op.drop_table('meta_campaign')
    op.drop_index('idx_gads_ts_client_date', table_name='google_ads_time_segments')
    op.drop_table('google_ads_time_segments')
    op.drop_index('idx_gads_st_client_date', table_name='google_ads_search_terms')
    op.drop_table('google_ads_search_terms')
    op.drop_index('idx_gads_kw_client_date', table_name='google_ads_keywords')
    op.drop_table('google_ads_keywords')
    op.drop_index('idx_gads_demo_client_date', table_name='google_ads_demographics')
    op.drop_table('google_ads_demographics')
    op.drop_index('idx_gads_camp_client_date', table_name='google_ads_campaign')
    op.drop_table('google_ads_campaign')
    op.drop_index('idx_ga4_rev_client_date', table_name='ga4_revenue')
    op.drop_table('ga4_revenue')
    op.drop_index('idx_ga4_dev_client_date', table_name='ga4_device_breakdown')
    op.drop_table('ga4_device_breakdown')
    op.drop_index('idx_ga4_ch_client_date', table_name='ga4_channel_breakdown')
    op.drop_table('ga4_channel_breakdown')
    op.drop_index('idx_pull_jobs_status', table_name='pull_jobs')
    op.drop_index('idx_pull_jobs_source', table_name='pull_jobs')
    op.drop_index('idx_pull_jobs_created', table_name='pull_jobs')
    op.drop_index('idx_pull_jobs_client', table_name='pull_jobs')
    op.drop_table('pull_jobs')
    op.drop_index('idx_connections_source', table_name='client_connections')
    op.drop_index('idx_connections_client', table_name='client_connections')
    op.drop_table('client_connections')
    op.drop_index('idx_clients_type', table_name='clients')
    op.drop_index('idx_clients_active', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
